# 00. PyTorch Fundamentals


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


## Introduction to Tensors


### Creating Tensors

PyTorch tensors are created using 'torch.Tensor()'

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.dim

<function Tensor.dim>

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [12]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [15]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# TENSOR
TENSOR = torch.tensor([[[7, 8],
                        [9, 10]],

                       [[11, 12],
                        [13, 14]]])
TENSOR

tensor([[[ 7,  8],
         [ 9, 10]],

        [[11, 12],
         [13, 14]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([2, 2, 2])

In [21]:
TENSOR[0]

tensor([[ 7,  8],
        [ 9, 10]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.



```
Start with random numbers -> look at data -> update random numbers -> update random number
```



In [25]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.6847, 0.4706, 0.3079, 0.4029],
         [0.1772, 0.3619, 0.8852, 0.6087],
         [0.0405, 0.8023, 0.9880, 0.1095]],

        [[0.3224, 0.9329, 0.4886, 0.9552],
         [0.7302, 0.1449, 0.5941, 0.8013],
         [0.5639, 0.2215, 0.5675, 0.0982]]])

In [29]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(244, 244, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and ones

In [30]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like


In [41]:
# Use torch.range()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = TENSOR)
ten_zeros

tensor([[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [49]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,          # what datatype is the tensor (e.g. float 32 or float16)
                               device = None,         # what device is your tensor on
                               requires_grad = False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [50]:
float_32_tensor.dtype

torch.float32

In [52]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)