<a href="https://colab.research.google.com/github/OmerZeyveli/pytorch-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


## Introduction to Tensors


### Creating Tensors

PyTorch tensors are created using 'torch.Tensor()'

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.dim

<function Tensor.dim>

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[7, 8],
                        [9, 10]],

                       [[11, 12],
                        [13, 14]]])
TENSOR

tensor([[[ 7,  8],
         [ 9, 10]],

        [[11, 12],
         [13, 14]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([2, 2, 2])

In [15]:
TENSOR[0]

tensor([[ 7,  8],
        [ 9, 10]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.



```
Start with random numbers -> look at data -> update random numbers -> update random number
```



In [16]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.1101, 0.6077, 0.9222, 0.4911],
         [0.7064, 0.6654, 0.2663, 0.8681],
         [0.2692, 0.8029, 0.6759, 0.6517]],

        [[0.3882, 0.1199, 0.5469, 0.7861],
         [0.9894, 0.7870, 0.6875, 0.9625],
         [0.7403, 0.9206, 0.7032, 0.9759]]])

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(244, 244, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and ones

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like


In [21]:
# Use torch.range()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = TENSOR)
ten_zeros

tensor([[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [23]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,          # what datatype is the tensor (e.g. float 32 or float16)
                               device = None,         # what device is your tensor on
                               requires_grad = False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [27]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use ```tensor.dtype```
2. Tensors not right shape - to get shape from a tensor, can use ```tensor.shape```
3. Tensors not on the right device - to get device from a tensor, can use ```tensor.device```

In [28]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3105, 0.8544, 0.1832, 0.3926],
        [0.9741, 0.5869, 0.2907, 0.5482],
        [0.7124, 0.7905, 0.0436, 0.2836]])

In [29]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.3105, 0.8544, 0.1832, 0.3926],
        [0.9741, 0.5869, 0.2907, 0.5482],
        [0.7124, 0.7905, 0.0436, 0.2836]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [30]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [31]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [32]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [33]:
# Divide tensor by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [34]:
# Modulus tensor by 2
tensor % 2

tensor([1, 0, 1])

In [35]:
# Try out PyTorch in-built functions
print(torch.add(tensor, 10))
print(torch.subtract(tensor, 10))
print(torch.multiply(tensor, 10))
print(torch.divide(tensor, 10))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* ```(3, 2) @ (3, 2)``` won't work
* ```(2, 3) @ (2, 3)``` won't work
* ```(2, 3) @ (3, 2)``` will work
* ```(3, 2) @ (2, 3)``` will work
2. The resulting matrix has the shape of **outer dimensions**:
* ```(2, 3) @ (3, 2)``` -> ```(2, 2)```
* ```(3, 2) @ (2, 3)``` -> ```(3, 3)```

In [36]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [37]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [38]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2 ms, sys: 20 µs, total: 2.02 ms
Wall time: 1.97 ms


In [39]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 485 µs, sys: 0 ns, total: 485 µs
Wall time: 422 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [41]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [42]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.


In [44]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [43]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])